import type { Metadata } from "next";
import { Manrope } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/custom/header";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/sonner";
import { CircleCheck } from "lucide-react";
import TokenRefresher from "@/components/custom/token-refresher";

const manrope = Manrope({ subsets: ['latin'], variable: "--font-manrope" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={cn("min-h-screen bg-background font-manrope antialiased", manrope.variable)}>
          <TokenRefresher>
            <Header />
            <main>{children}</main>
            <Toaster closeButton={true} position="top-center" />
          </TokenRefresher>
        </body>
      </StoreProvider>

    </html>
  );
}
